name: build

on:
  schedule:
    - cron: "42 6 * * *"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    outputs:
      tag: ${{ steps.result.outputs.tag }}

    steps:
      - name: Get upstream tag
        id: upstream-tag
        run: |
          result=$(gh release list --repo restic/restic --limit 1 --exclude-drafts --json tagName --jq '.[] |.tagName')

          if [ $? -ne 0 ]
          then
            exit $?
          fi

          echo $result

          echo "tag=$result" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Get downstream tag
        id: downstream-tag
        run: |
          result=$(gh release list --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} --limit 1 --exclude-drafts --json tagName --jq '.[] |.tagName')

          if [ $? -ne 0 ]
          then
            exit $?
          fi

          echo $result

          echo "tag=$result" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Result
        id: result
        shell: pwsh
        run: |
          $upstreamVersion = [Version]::new('${{ steps.upstream-tag.outputs.tag }}'.TrimStart('v'))

          if ('${{ steps.downstream-tag.outputs.tag }}')
          {
            $downstreamVersion = [Version]::new('${{ steps.downstream-tag.outputs.tag }}'.TrimStart('v'))
          }
          else
          {
            $downstreamVersion = [Version]::new()
          }

          if ($upstreamVersion -gt $downstreamVersion)
          {
            echo 'Build is required.'
            "tag=${{ steps.upstream-tag.outputs.tag }}" >> $env:GITHUB_OUTPUT
          }
          else
          {
            echo 'Build not required.'
          }

  build:
    runs-on: windows-latest
    timeout-minutes: 10
    needs: check
    if: needs.check.outputs.tag != ''

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          $tag = "${{ needs.check.outputs.tag }}".TrimStart("v")
          $version = [version]::new($tag)
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "versionMajor=$($version.Major)" >> $env:GITHUB_OUTPUT
          echo "versionMinor=$($version.Minor)" >> $env:GITHUB_OUTPUT
          echo "versionBuild=$($version.Build)" >> $env:GITHUB_OUTPUT

      - name: Setup wix
        run: |
          dotnet.exe tool install --global wix --version 5.0.2 --verbosity diag

          wix.exe extension add WixToolset.UI.wixext/5.0.2 --global
          wix.exe extension add WixToolset.Util.wixext/5.0.2 --global
          wix.exe extension list --global

      - name: Download restic
        run: |
          gh.exe release download ${{ needs.check.outputs.tag }} --pattern '*_windows_amd64.zip' --repo restic/restic
          Get-ChildItem
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract restic
        id: extract
        run: |
          New-Item -Name tmp -ItemType Directory -ErrorAction Stop |Out-Null
          Expand-Archive -Path '*_windows_amd64.zip' -DestinationPath tmp -ErrorAction Stop
          Get-ChildItem -Path tmp -Recurse
          New-Item -Name build -ItemType Directory -ErrorAction Stop |Out-Null
          $path = Move-Item -Path ./tmp/*_windows_amd64.exe -Destination ./build/restic.exe -PassThru -ErrorAction Stop
          echo "path=$path" >> $env:GITHUB_OUTPUT

      - name: Build installer
        run: |
          wix.exe `
            build `
            -arch x64 `
            -src src\Product.wxs `
            -d ProductSource="${{ steps.extract.outputs.path }}" `
            -d ProductVersion="${{ steps.version.outputs.version }}" `
            -ext WixToolset.UI.wixext `
            -out restic.msi

      - name: Validate installer
        run: wix.exe msi validate restic.msi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: restic-msi
          path: ./restic.msi
          if-no-files-found: error

      - name: Test installer
        run: |
          $process = Start-Process msiexec.exe -ArgumentList '/i','restic.msi','/qn' -Wait -NoNewWindow -PassThru -ErrorAction Stop
          if ($process.ExitCode -ne 0)
          {
              throw 'Non zero exit code: "{0}".' -f $process.ExitCode
          }

          $path = Join-Path $env:ProgramFiles 'restic\restic.exe'
          & $path version

      - name: Publish release
        run: gh.exe release create ${{ needs.check.outputs.tag }} --notes 'Restic Windows build packaged as an msi.' restic.msi
        env:
          # Requires a personal access token with a fine-grained permission of contents:read/write.
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
